nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports: 
        - "80:80"
        - "443:443"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - /data/certs/:/etc/nginx/certs:ro
        - /etc/nginx/vhost.d
        - /usr/share/nginx/html
    labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_prox

letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
        - /data/certs:/etc/nginx/certs:rw
        - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
        - nginx-proxy:rw

www:
    image: nginx:1.17.8
    restart: always
    expose:
        - "80"
    volumes:
        - /home/soporte/docker-nginx-letsencrypt/www:/usr/share/nginx/html:ro
    environment:
        - VIRTUAL_HOST=sisglobal.local,www.sisglobal.local
        - LETSENCRYPT_HOST=sisglobal.local,www.sisglobal.local
        - LETSENCRYPT_EMAIL=sysadm2.acero@gmail.com

www2:
    image: nginx:1.17.8
    restart: always
    expose:
        - "80"
    volumes:
        - /home/soporte/docker-nginx-letsencrypt/www2:/usr/share/nginx/html:ro
    environment:
        - VIRTUAL_HOST=sisglobaltest.local,www.sisglobaltest.local
        - LETSENCRYPT_HOST=sisglobaltest.local,www.sisglobaltest.local
        - LETSENCRYPT_EMAIL=sysadm2.acero@gmail.com


